import postgres from 'postgres';
import { DB, PID } from './e2e-lib.mjs';
const sql = postgres(DB);
const [b] = await sql`select id, batch_id, status, request, created_at from forge.ops_mma_batch where project_id=${PID} and handler='execute-pipeline' order by created_at desc limit 1`;
console.log('execute batch:', b?.status, '| age(s):', b ? Math.round((Date.now()-b.created_at.getTime())/1000) : 'n/a');
const req = b?.request;
console.log('request repo/branch:', JSON.stringify({ targetBranch: req?.targetBranch, repoId: req?.repoId, cwd: req?.cwd, tasks: req?.tasks?.length ?? req?.taskHeadings?.length }).slice(0,200));
const [p] = await sql`select details from forge.project where id=${PID}`;
const ex = p.details.stages.execute;
console.log('execute phase:', ex.phases.configure.status, '/', ex.phases.implement.status, '| runs:', JSON.stringify(ex.phases.implement.runs?.map(r=>({repo:r.repoId?.slice(0,8), status:r.status})) ?? ex.phases.implement.repos?.map(r=>({s:r.status})) ?? 'n/a'));
await sql.end();
